<?xml version="1.0" ?>
<robot name="handed_robot" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- ========================== UR10 ================================ -->
    <xacro:include filename="$(find ur_description)/urdf/ur10.urdf.xacro" />
    <!-- arm -->
    <xacro:ur10_robot prefix="" joint_limited="false"/>

    <link name="world" />

    <joint name="world_joint" type="fixed">
      <parent link="world" />
      <child link = "base_link" />
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </joint>

    <!-- ========================== END ================================= -->

    <!-- ========================== HAND ================================ -->
    <xacro:include filename="$(find ur_gym)/objects/allegro_hand_modified_urdf/allegro_hand_description_right.urdf.xacro"/>

    <joint name="arm_to_hand_joint" type="fixed">
        <origin xyz="0 ${wrist_3_length+0.095} 0" rpy="${pi/-2.0} 0 0"/>
        <limit effort="400" velocity="3"/>
        <parent link="wrist_3_link"/>
        <child link="hand_base_link"/>
    </joint>

    <!-- ========================== END ================================= -->

    <!-- ========================== PLUGIN ============================== -->
    <gazebo>
      <plugin name="ros_control" filename="libgazebo_ros_control.so"/>
    </gazebo>

    <!-- ========================== END ================================= -->

</robot>
