// Auto-generated. Do not edit!

// (in-package ur_moveit_planner.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class moveToCartesianPoseResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.motionComplete = null;
    }
    else {
      if (initObj.hasOwnProperty('motionComplete')) {
        this.motionComplete = initObj.motionComplete
      }
      else {
        this.motionComplete = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type moveToCartesianPoseResult
    // Serialize message field [motionComplete]
    bufferOffset = _serializer.bool(obj.motionComplete, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type moveToCartesianPoseResult
    let len;
    let data = new moveToCartesianPoseResult(null);
    // Deserialize message field [motionComplete]
    data.motionComplete = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ur_moveit_planner/moveToCartesianPoseResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9f739e08659d6e65dcea7b75b197c1e0';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #outputs
    bool motionComplete
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new moveToCartesianPoseResult(null);
    if (msg.motionComplete !== undefined) {
      resolved.motionComplete = msg.motionComplete;
    }
    else {
      resolved.motionComplete = false
    }

    return resolved;
    }
};

module.exports = moveToCartesianPoseResult;
