// Generated by gencpp from file ur_moveit_planner/currentPose.msg
// DO NOT EDIT!


#ifndef UR_MOVEIT_PLANNER_MESSAGE_CURRENTPOSE_H
#define UR_MOVEIT_PLANNER_MESSAGE_CURRENTPOSE_H

#include <ros/service_traits.h>


#include <ur_moveit_planner/currentPoseRequest.h>
#include <ur_moveit_planner/currentPoseResponse.h>


namespace ur_moveit_planner
{

struct currentPose
{

typedef currentPoseRequest Request;
typedef currentPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct currentPose
} // namespace ur_moveit_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_moveit_planner::currentPose > {
  static const char* value()
  {
    return "6c87b4584c2caa9989c95fc8615bf690";
  }

  static const char* value(const ::ur_moveit_planner::currentPose&) { return value(); }
};

template<>
struct DataType< ::ur_moveit_planner::currentPose > {
  static const char* value()
  {
    return "ur_moveit_planner/currentPose";
  }

  static const char* value(const ::ur_moveit_planner::currentPose&) { return value(); }
};


// service_traits::MD5Sum< ::ur_moveit_planner::currentPoseRequest> should match 
// service_traits::MD5Sum< ::ur_moveit_planner::currentPose > 
template<>
struct MD5Sum< ::ur_moveit_planner::currentPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_moveit_planner::currentPose >::value();
  }
  static const char* value(const ::ur_moveit_planner::currentPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_moveit_planner::currentPoseRequest> should match 
// service_traits::DataType< ::ur_moveit_planner::currentPose > 
template<>
struct DataType< ::ur_moveit_planner::currentPoseRequest>
{
  static const char* value()
  {
    return DataType< ::ur_moveit_planner::currentPose >::value();
  }
  static const char* value(const ::ur_moveit_planner::currentPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_moveit_planner::currentPoseResponse> should match 
// service_traits::MD5Sum< ::ur_moveit_planner::currentPose > 
template<>
struct MD5Sum< ::ur_moveit_planner::currentPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_moveit_planner::currentPose >::value();
  }
  static const char* value(const ::ur_moveit_planner::currentPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_moveit_planner::currentPoseResponse> should match 
// service_traits::DataType< ::ur_moveit_planner::currentPose > 
template<>
struct DataType< ::ur_moveit_planner::currentPoseResponse>
{
  static const char* value()
  {
    return DataType< ::ur_moveit_planner::currentPose >::value();
  }
  static const char* value(const ::ur_moveit_planner::currentPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MOVEIT_PLANNER_MESSAGE_CURRENTPOSE_H
