// Generated by gencpp from file ur_moveit_planner/moveToCartesianPoseRequest.msg
// DO NOT EDIT!


#ifndef UR_MOVEIT_PLANNER_MESSAGE_MOVETOCARTESIANPOSEREQUEST_H
#define UR_MOVEIT_PLANNER_MESSAGE_MOVETOCARTESIANPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace ur_moveit_planner
{
template <class ContainerAllocator>
struct moveToCartesianPoseRequest_
{
  typedef moveToCartesianPoseRequest_<ContainerAllocator> Type;

  moveToCartesianPoseRequest_()
    : target_pose()  {
    }
  moveToCartesianPoseRequest_(const ContainerAllocator& _alloc)
    : target_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;




  typedef boost::shared_ptr< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct moveToCartesianPoseRequest_

typedef ::ur_moveit_planner::moveToCartesianPoseRequest_<std::allocator<void> > moveToCartesianPoseRequest;

typedef boost::shared_ptr< ::ur_moveit_planner::moveToCartesianPoseRequest > moveToCartesianPoseRequestPtr;
typedef boost::shared_ptr< ::ur_moveit_planner::moveToCartesianPoseRequest const> moveToCartesianPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur_moveit_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ur_moveit_planner': ['/home/wzc/cat_ws/src/ur_moveit_planner/msg', '/home/wzc/cat_ws/devel/share/ur_moveit_planner/msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "671ab81f81ce3fa4e8a3ac70c41ddb7c";
  }

  static const char* value(const ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x671ab81f81ce3fa4ULL;
  static const uint64_t static_value2 = 0xe8a3ac70c41ddb7cULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_moveit_planner/moveToCartesianPoseRequest";
  }

  static const char* value(const ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Pose target_pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveToCartesianPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur_moveit_planner::moveToCartesianPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR_MOVEIT_PLANNER_MESSAGE_MOVETOCARTESIANPOSEREQUEST_H
