// Generated by gencpp from file ur_moveit_planner/moveToJointAngles.msg
// DO NOT EDIT!


#ifndef UR_MOVEIT_PLANNER_MESSAGE_MOVETOJOINTANGLES_H
#define UR_MOVEIT_PLANNER_MESSAGE_MOVETOJOINTANGLES_H

#include <ros/service_traits.h>


#include <ur_moveit_planner/moveToJointAnglesRequest.h>
#include <ur_moveit_planner/moveToJointAnglesResponse.h>


namespace ur_moveit_planner
{

struct moveToJointAngles
{

typedef moveToJointAnglesRequest Request;
typedef moveToJointAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct moveToJointAngles
} // namespace ur_moveit_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_moveit_planner::moveToJointAngles > {
  static const char* value()
  {
    return "aa7ce802f4cb34d824a06bc1621a7d9e";
  }

  static const char* value(const ::ur_moveit_planner::moveToJointAngles&) { return value(); }
};

template<>
struct DataType< ::ur_moveit_planner::moveToJointAngles > {
  static const char* value()
  {
    return "ur_moveit_planner/moveToJointAngles";
  }

  static const char* value(const ::ur_moveit_planner::moveToJointAngles&) { return value(); }
};


// service_traits::MD5Sum< ::ur_moveit_planner::moveToJointAnglesRequest> should match 
// service_traits::MD5Sum< ::ur_moveit_planner::moveToJointAngles > 
template<>
struct MD5Sum< ::ur_moveit_planner::moveToJointAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_moveit_planner::moveToJointAngles >::value();
  }
  static const char* value(const ::ur_moveit_planner::moveToJointAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_moveit_planner::moveToJointAnglesRequest> should match 
// service_traits::DataType< ::ur_moveit_planner::moveToJointAngles > 
template<>
struct DataType< ::ur_moveit_planner::moveToJointAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::ur_moveit_planner::moveToJointAngles >::value();
  }
  static const char* value(const ::ur_moveit_planner::moveToJointAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_moveit_planner::moveToJointAnglesResponse> should match 
// service_traits::MD5Sum< ::ur_moveit_planner::moveToJointAngles > 
template<>
struct MD5Sum< ::ur_moveit_planner::moveToJointAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_moveit_planner::moveToJointAngles >::value();
  }
  static const char* value(const ::ur_moveit_planner::moveToJointAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_moveit_planner::moveToJointAnglesResponse> should match 
// service_traits::DataType< ::ur_moveit_planner::moveToJointAngles > 
template<>
struct DataType< ::ur_moveit_planner::moveToJointAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::ur_moveit_planner::moveToJointAngles >::value();
  }
  static const char* value(const ::ur_moveit_planner::moveToJointAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MOVEIT_PLANNER_MESSAGE_MOVETOJOINTANGLES_H
