; Auto-generated. Do not edit!


(cl:in-package ur_moveit_planner-msg)


;//! \htmlinclude moveToJointAnglesFeedback.msg.html

(cl:defclass <moveToJointAnglesFeedback> (roslisp-msg-protocol:ros-message)
  ((motionComplete
    :reader motionComplete
    :initarg :motionComplete
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass moveToJointAnglesFeedback (<moveToJointAnglesFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveToJointAnglesFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveToJointAnglesFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ur_moveit_planner-msg:<moveToJointAnglesFeedback> is deprecated: use ur_moveit_planner-msg:moveToJointAnglesFeedback instead.")))

(cl:ensure-generic-function 'motionComplete-val :lambda-list '(m))
(cl:defmethod motionComplete-val ((m <moveToJointAnglesFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ur_moveit_planner-msg:motionComplete-val is deprecated.  Use ur_moveit_planner-msg:motionComplete instead.")
  (motionComplete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveToJointAnglesFeedback>) ostream)
  "Serializes a message object of type '<moveToJointAnglesFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'motionComplete) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveToJointAnglesFeedback>) istream)
  "Deserializes a message object of type '<moveToJointAnglesFeedback>"
    (cl:setf (cl:slot-value msg 'motionComplete) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveToJointAnglesFeedback>)))
  "Returns string type for a message object of type '<moveToJointAnglesFeedback>"
  "ur_moveit_planner/moveToJointAnglesFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveToJointAnglesFeedback)))
  "Returns string type for a message object of type 'moveToJointAnglesFeedback"
  "ur_moveit_planner/moveToJointAnglesFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveToJointAnglesFeedback>)))
  "Returns md5sum for a message object of type '<moveToJointAnglesFeedback>"
  "9f739e08659d6e65dcea7b75b197c1e0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveToJointAnglesFeedback)))
  "Returns md5sum for a message object of type 'moveToJointAnglesFeedback"
  "9f739e08659d6e65dcea7b75b197c1e0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveToJointAnglesFeedback>)))
  "Returns full string definition for message of type '<moveToJointAnglesFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback message~%bool motionComplete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveToJointAnglesFeedback)))
  "Returns full string definition for message of type 'moveToJointAnglesFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback message~%bool motionComplete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveToJointAnglesFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveToJointAnglesFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'moveToJointAnglesFeedback
    (cl:cons ':motionComplete (motionComplete msg))
))
