; Auto-generated. Do not edit!


(cl:in-package ur_moveit_planner-msg)


;//! \htmlinclude moveToJointAnglesActionGoal.msg.html

(cl:defclass <moveToJointAnglesActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type ur_moveit_planner-msg:moveToJointAnglesGoal
    :initform (cl:make-instance 'ur_moveit_planner-msg:moveToJointAnglesGoal)))
)

(cl:defclass moveToJointAnglesActionGoal (<moveToJointAnglesActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveToJointAnglesActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveToJointAnglesActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ur_moveit_planner-msg:<moveToJointAnglesActionGoal> is deprecated: use ur_moveit_planner-msg:moveToJointAnglesActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <moveToJointAnglesActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ur_moveit_planner-msg:header-val is deprecated.  Use ur_moveit_planner-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <moveToJointAnglesActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ur_moveit_planner-msg:goal_id-val is deprecated.  Use ur_moveit_planner-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <moveToJointAnglesActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ur_moveit_planner-msg:goal-val is deprecated.  Use ur_moveit_planner-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveToJointAnglesActionGoal>) ostream)
  "Serializes a message object of type '<moveToJointAnglesActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveToJointAnglesActionGoal>) istream)
  "Deserializes a message object of type '<moveToJointAnglesActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveToJointAnglesActionGoal>)))
  "Returns string type for a message object of type '<moveToJointAnglesActionGoal>"
  "ur_moveit_planner/moveToJointAnglesActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveToJointAnglesActionGoal)))
  "Returns string type for a message object of type 'moveToJointAnglesActionGoal"
  "ur_moveit_planner/moveToJointAnglesActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveToJointAnglesActionGoal>)))
  "Returns md5sum for a message object of type '<moveToJointAnglesActionGoal>"
  "6cbfda2ea142001a80e3669b41068c46")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveToJointAnglesActionGoal)))
  "Returns md5sum for a message object of type 'moveToJointAnglesActionGoal"
  "6cbfda2ea142001a80e3669b41068c46")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveToJointAnglesActionGoal>)))
  "Returns full string definition for message of type '<moveToJointAnglesActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%moveToJointAnglesGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: ur_moveit_planner/moveToJointAnglesGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#inputs~%float32 a1~%float32 a2~%float32 a3~%float32 a4~%float32 a5~%float32 a6~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveToJointAnglesActionGoal)))
  "Returns full string definition for message of type 'moveToJointAnglesActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%moveToJointAnglesGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: ur_moveit_planner/moveToJointAnglesGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#inputs~%float32 a1~%float32 a2~%float32 a3~%float32 a4~%float32 a5~%float32 a6~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveToJointAnglesActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveToJointAnglesActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'moveToJointAnglesActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
