; Auto-generated. Do not edit!


(cl:in-package ur_moveit_planner-msg)


;//! \htmlinclude moveToCartesianPoseResult.msg.html

(cl:defclass <moveToCartesianPoseResult> (roslisp-msg-protocol:ros-message)
  ((motionComplete
    :reader motionComplete
    :initarg :motionComplete
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass moveToCartesianPoseResult (<moveToCartesianPoseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveToCartesianPoseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveToCartesianPoseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ur_moveit_planner-msg:<moveToCartesianPoseResult> is deprecated: use ur_moveit_planner-msg:moveToCartesianPoseResult instead.")))

(cl:ensure-generic-function 'motionComplete-val :lambda-list '(m))
(cl:defmethod motionComplete-val ((m <moveToCartesianPoseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ur_moveit_planner-msg:motionComplete-val is deprecated.  Use ur_moveit_planner-msg:motionComplete instead.")
  (motionComplete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveToCartesianPoseResult>) ostream)
  "Serializes a message object of type '<moveToCartesianPoseResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'motionComplete) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveToCartesianPoseResult>) istream)
  "Deserializes a message object of type '<moveToCartesianPoseResult>"
    (cl:setf (cl:slot-value msg 'motionComplete) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveToCartesianPoseResult>)))
  "Returns string type for a message object of type '<moveToCartesianPoseResult>"
  "ur_moveit_planner/moveToCartesianPoseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveToCartesianPoseResult)))
  "Returns string type for a message object of type 'moveToCartesianPoseResult"
  "ur_moveit_planner/moveToCartesianPoseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveToCartesianPoseResult>)))
  "Returns md5sum for a message object of type '<moveToCartesianPoseResult>"
  "9f739e08659d6e65dcea7b75b197c1e0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveToCartesianPoseResult)))
  "Returns md5sum for a message object of type 'moveToCartesianPoseResult"
  "9f739e08659d6e65dcea7b75b197c1e0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveToCartesianPoseResult>)))
  "Returns full string definition for message of type '<moveToCartesianPoseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#outputs~%bool motionComplete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveToCartesianPoseResult)))
  "Returns full string definition for message of type 'moveToCartesianPoseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#outputs~%bool motionComplete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveToCartesianPoseResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveToCartesianPoseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'moveToCartesianPoseResult
    (cl:cons ':motionComplete (motionComplete msg))
))
